name: $(MajorVersion).$(MinorVersion)$(rev:.r)
pool:
  name: Default

trigger:
  branches:
    include:
      - master

steps:
- task: DockerInstaller@0
  displayName: Docker Installer
  inputs:
    dockerVersion: 18.03.0-ce
    releaseType: stable

- task: Docker@2
  displayName: Build and Push Image to Docker Hub
  inputs:
    containerRegistry: 'docker-hub'
    repository: 'canhorn/ehz-platform-server-core'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    buildContext: $(Build.SourcesDirectory)
    tags: |
      $(Build.BuildNumber)
      latest
